id: IAA423989
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:03:26+00:00'
last_modified: '2022-06-07T12:03:02.215913+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16611
  title: ཐུབ་པའི་གསུང་གི་སྙིང་པོར་གྱུར་པ་ཆེད་དུ་བརྗོད་པའི་ཚོམས་ཞེས་བྱ་བའི་རྣམ་པར་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2F3A:
      image_group_id: I1KG16657
      title: Volume 1 of thub pa'i gsung gi snying por gyur pa ched du brjod pa'i
        tshoms zhes bya ba'i rnam par 'grel pa/
      total_pages: 882
      order: 1
      base_file: 2F3A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
